name: EasyBrag
main: skyss0fly\EasyBrag\Main
version: 1.2.0
api: 5.0.0
author: [skyss0fly, Levonzie]
description: A simple bragging plugin
permissions:
  easybrag.use:
    default: true
  easybrag.cooldown_bypass:
    default: op
commands:
  brag:
    description: brag the item you have in your hand!
    permission: easybrag.use
    default: true
  
